__author__ = 'arenduchintala'

BOUNDARY_START = "#START#"
BOUNDARY_END = "#END#"
NULL = "NULL"
E_TYPE = "EMISSION"
E_TYPE_PRE = "PREFIX_FEATURE"
E_TYPE_SUF = "SUFFIX_FEATURE"
T_TYPE = "TRANSITION"
ALL = "ALL_STATES"
IBM_MODEL_1 = "model1"
HYBRID_MODEL_1 = "hybrid-model1"
HMM_MODEL = "hmm"
EPS = 1e-5
Po = 0.08

